version: '3.1'
services:
  postgres:
    image: 'postgres:14.1'
    restart: always
    ports:
      - 5951:5432
    environment:
      ENVIRONMENT: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demodb
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - $HOME/Data/queryengine_demo:/var/lib/postgresql/data 
    networks:
      default:
        ipv4_address: 172.57.1.10
networks:
  default:
    ipam:
      config:
        - subnet: 172.57.1.0/24
